services:
  mysql:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  app:
    build: .
    ports:
      - "8080:8080"
    
