services:
  mysql:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  app:
    build: .
    ports:
      - "8080:8080"
    
